# services:
#   app:
#     build:
#       context: .
#       target: runner
#     env_file:
#       - .env
#     ports:
#       - "8080:3000"
#     volumes:
#       - ./app.js:/app/app.js
#       - ./public:/app/public
#       - /app/node_modules
#     # command: ["nodemon", "app.js"]
#     command: npm run dev
#     restart: unless-stopped
services:
  app:
    build:
      context: .
      # target: runner

    env_file:
      - .env

    ports:
      - "8080:3000"

    restart: unless-stopped
